"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var album_1 = require("./album");
var library_1 = require("./library");
var fs_1 = require("fs");
var fileData = fs_1.readFileSync('./practiceData.js').toString();
//console.log(fileData);
var albumInfo = JSON.parse(fileData);
var sourceList = [];
albumInfo.forEach(function (item) { return sourceList.push(album_1.Album.loadJson(JSON.stringify(item))); });
var testLibrary = new library_1.Library(sourceList);
//testLibrary.selected.consoleLog();
console.log("Page " + testLibrary.currentPage + " of " + testLibrary.numberOfPages);
console.log("Selected album -- " + testLibrary.selected.getString());
console.log("");
testLibrary.setCurrentPage(29);
console.log("Page " + testLibrary.currentPage + " of " + testLibrary.numberOfPages);
console.log("Selected album -- " + testLibrary.selected.getString());
console.log('');
testLibrary.setSelectedAlbum(12);
console.log("Page " + testLibrary.currentPage + " of " + testLibrary.numberOfPages);
console.log("Selected album -- " + testLibrary.selected.getString());
console.log('');
testLibrary.setSelectedAlbum(49);
console.log("Page " + testLibrary.currentPage + " of " + testLibrary.numberOfPages);
console.log("Selected album -- " + testLibrary.selected.getString());
console.log('');
testLibrary.setSelectedAlbum(288);
console.log("Page " + testLibrary.currentPage + " of " + testLibrary.numberOfPages);
console.log("Selected album -- " + testLibrary.selected.getString());
console.log('');
var albumToAdd = new album_1.Album('Electric Light Orchestra', 'Out Of The Blue');
testLibrary.addAlbum(albumToAdd);
console.log("Page " + testLibrary.currentPage + " of " + testLibrary.numberOfPages);
console.log("Selected album -- " + testLibrary.selected.getString());
console.log('');
testLibrary.editSelectedAlbum('The Electric Light Orchestra', 'Out of the Blue');
console.log("Page " + testLibrary.currentPage + " of " + testLibrary.numberOfPages);
console.log("Selected album -- " + testLibrary.selected.getString());
console.log('');
testLibrary.deleteSelectedAlbum();
console.log("Page " + testLibrary.currentPage + " of " + testLibrary.numberOfPages);
console.log("Selected album -- " + testLibrary.selected.getString());
console.log('');
