"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var album_1 = require("./album");
var libraryPersist_1 = require("./libraryPersist");
var testLibrary = libraryPersist_1.LibraryPersist.libraryFromFile('./albums.txt');
console.log("Page " + testLibrary.currentPage + " of " + testLibrary.numberOfPages);
console.log("Selected album -- " + testLibrary.selected.getString());
console.log("");
testLibrary.setCurrentPage(30);
console.log("Page " + testLibrary.currentPage + " of " + testLibrary.numberOfPages);
console.log("Selected album -- " + testLibrary.selected.getString());
console.log('');
testLibrary.setSelectedAlbum(12);
console.log("Page " + testLibrary.currentPage + " of " + testLibrary.numberOfPages);
console.log("Selected album -- " + testLibrary.selected.getString());
console.log('');
testLibrary.setSelectedAlbum(49);
console.log("Page " + testLibrary.currentPage + " of " + testLibrary.numberOfPages);
console.log("Selected album -- " + testLibrary.selected.getString());
console.log('');
testLibrary.setSelectedAlbum(294);
console.log("Page " + testLibrary.currentPage + " of " + testLibrary.numberOfPages);
console.log("Selected album -- " + testLibrary.selected.getString());
console.log('');
var albumToAdd = new album_1.Album('Electric Light Orchestra', 'Out Of The Blue', '1977');
testLibrary.addAlbum(albumToAdd);
console.log("Page " + testLibrary.currentPage + " of " + testLibrary.numberOfPages);
console.log("Selected album -- " + testLibrary.selected.getString());
console.log('');
testLibrary.editSelectedAlbum('The Electric Light Orchestra', 'Out of the Blue');
console.log("Page " + testLibrary.currentPage + " of " + testLibrary.numberOfPages);
console.log("Selected album -- " + testLibrary.selected.getString());
console.log('');
testLibrary.deleteSelectedAlbum();
console.log("Page " + testLibrary.currentPage + " of " + testLibrary.numberOfPages);
console.log("Selected album -- " + testLibrary.selected.getString());
console.log('');
