"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var practiceData_1 = require("./practiceData");
var album_1 = require("./album");
var library_1 = require("./library");
var p1 = practiceData_1.practice[0];
var sourceList = [];
practiceData_1.practice.forEach(function (item) { return sourceList.push(album_1.Album.loadJson(JSON.stringify(item))); });
var testLibrary = new library_1.Library(sourceList);
//testLibrary.selected.consoleLog();
console.log("Page " + testLibrary.currentPage + " of " + testLibrary.numberOfPages);
console.log("Selected album -- " + testLibrary.selected.getString());
console.log("");
testLibrary.setCurrentPage(29);
console.log("Page " + testLibrary.currentPage + " of " + testLibrary.numberOfPages);
console.log("Selected album -- " + testLibrary.selected.getString());
console.log('');
testLibrary.setSelectedAlbum(12);
console.log("Page " + testLibrary.currentPage + " of " + testLibrary.numberOfPages);
console.log("Selected album -- " + testLibrary.selected.getString());
console.log('');
testLibrary.setSelectedAlbum(49);
console.log("Page " + testLibrary.currentPage + " of " + testLibrary.numberOfPages);
console.log("Selected album -- " + testLibrary.selected.getString());
console.log('');
testLibrary.setSelectedAlbum(288);
console.log("Page " + testLibrary.currentPage + " of " + testLibrary.numberOfPages);
console.log("Selected album -- " + testLibrary.selected.getString());
