"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.practice = void 0;
exports.practice = [{ "artist": "2pac", "name": "All Eyez On Me" },
    { "artist": "3 Doors Down", "name": "The Greatest Hits" },
    { "artist": "3 Doors Down", "name": "A Better Life" },
    { "artist": "Adele", "name": "21" },
    { "artist": "Alanis Morissette", "name": "Jagged Little Pill" },
    { "artist": "Alphaville", "name": "Forever Young" },
    { "artist": "Amy Winehouse", "name": "Back To Black" },
    { "artist": "Arcade Fire", "name": "Neon Bible" },
    { "artist": "Audioslave", "name": "Audioslave" },
    { "artist": "Augustana", "name": "Augustana" },
    { "artist": "Augustana", "name": "Life Imitating Life" },
    { "artist": "AWOLNATION", "name": "Here Come The Runts" },
    { "artist": "AWOLNATION", "name": "Megalithic Symphony" },
    { "artist": "B.o.B.", "name": "Strange Clouds" },
    { "artist": "Band Of Skulls", "name": "Baby Darling Doll Face Honey" },
    { "artist": "Band Of Skulls", "name": "Love Is All You Love" },
    { "artist": "Bastille", "name": "Bad Blood" },
    { "artist": "Bebe", "name": "Un Pokito De Rocanrol" },
    { "artist": "Bebe", "name": "Y." },
    { "artist": "Beck", "name": "Odelay" },
    { "artist": "Belly", "name": "Immigrant" },
    { "artist": "Berlin", "name": "Love Life" },
    { "artist": "Billy Joel", "name": "52nd Street" },
    { "artist": "Billy Joel", "name": "The Stranger" },
    { "artist": "Blitzen Trapper", "name": "VII" },
    { "artist": "Blitzen Trapper", "name": "Wild And Reckless" },
    { "artist": "Blondie", "name": "Eat To The Beat" },
    { "artist": "Blondie", "name": "Parallel Lines" },
    { "artist": "Blue October", "name": "Foiled" },
    { "artist": "Blue Oyster Cult", "name": "Cultosauros Erectus" },
    { "artist": "Blue Oyster Cult", "name": "Spectres" },
    { "artist": "Blues Traveller", "name": "Four" },
    { "artist": "Bob Dylan", "name": "Blood On The Tracks" },
    { "artist": "Bonde do Rolê", "name": "Tropicalbacanal" },
    { "artist": "Boogie", "name": "Everythings For Sale" },
    { "artist": "Brandi Carlile", "name": "Bear Creek" },
    { "artist": "Broken Bells", "name": "Broken Bells" },
    { "artist": "Bruce Springsteen", "name": "Born In The U.S.A." },
    { "artist": "Bruce Springsteen", "name": "Darkness On The Edge Of Town" },
    { "artist": "Bruce Springsteen", "name": "Wrecking Ball" },
    { "artist": "Cake", "name": "Comfort Eagle" },
    { "artist": "Cake", "name": "Prolonging The Magic" },
    { "artist": "Chris Stapleton", "name": "From A Room: Volume 1" },
    { "artist": "Chris Stapleton", "name": "Traveller" },
    { "artist": "Christina Perri", "name": "Lovestrong" },
    { "artist": "Chvrches", "name": "Every Open Eye" },
    { "artist": "Chvrches", "name": "The Bones Of What You Believe" },
    { "artist": "Chvrches", "name": "Love Is Dead" },
    { "artist": "Civil Twilight", "name": "Holy Weather" },
    { "artist": "Civil Twilight", "name": "Civil Twilight" },
    { "artist": "Coast Modern", "name": "Coast Modern" },
    { "artist": "Death Cab For Cutie", "name": "Codes And Keys" },
    { "artist": "Death Cab For Cutie", "name": "Narrow Stairs" },
    { "artist": "Death Cab For Cutie", "name": "Plans" },
    { "artist": "Dengue Fever", "name": "The Deepest Lake" },
    { "artist": "Depeche Mode", "name": "Violator" },
    { "artist": "Divine Fits", "name": "A Thing Called Divine Fits" },
    { "artist": "Dropkick Murpheys", "name": "Going Out In Style" },
    { "artist": "Dropkick Murpheys", "name": "SIGNED And SEALED In BLOOD" },
    { "artist": "Ed Sheeran", "name": "+" },
    { "artist": "Ed Sheeran", "name": "x" },
    { "artist": "Electric Light Orchestra", "name": "Time" },
    { "artist": "Eminem", "name": "Kamikaze" },
    { "artist": "Eurythmics", "name": "Ultimate Collection" },
    { "artist": "Evanescence", "name": "Evanescence" },
    { "artist": "Evanescence", "name": "Fallen" },
    { "artist": "Everclear", "name": "Invisible Stars" },
    { "artist": "Everclear", "name": "So Much For The Afterglow" },
    { "artist": "Fall Out Boy", "name": "American Beauty/American Psycho" },
    { "artist": "Fall Out Boy", "name": "From Under The Cork Tree" },
    { "artist": "Fall Out Boy", "name": "M A N I A" },
    { "artist": "Falling In Reverse", "name": "Coming Home" },
    { "artist": "Ferdinand the Bull", "name": "Painting Over Pictures" },
    { "artist": "Fitz And The Tantrums", "name": "More Than Just A Dream" },
    { "artist": "Foals", "name": "Everything Not Saved Will Be Lost Part 1" },
    { "artist": "Foreigner", "name": "Double Vision" },
    { "artist": "Fort Minor", "name": "The Rising Tied" },
    { "artist": "Foster The People", "name": "Torches" },
    { "artist": "fun.", "name": "Some Nights" },
    { "artist": "G. Love And Special Sauce", "name": "G. Love And Special Sauce" },
    { "artist": "G. Love And Special Sauce", "name": "Yeah, It's That Easy" },
    { "artist": "Gin Wigmore", "name": "Holy Smoke" },
    { "artist": "Gorillaz", "name": "Demon Days" },
    { "artist": "Gossip", "name": "A Joyful Noise" },
    { "artist": "Gossip", "name": "Music For Men" },
    { "artist": "Gotye", "name": "Making Mirrors" },
    { "artist": "Green Day", "name": "¡DOS!" },
    { "artist": "Green Day", "name": "¡TRÉ!" },
    { "artist": "Green Day", "name": "¡UNO!" },
    { "artist": "Green Day", "name": "American Idiot" },
    { "artist": "GRiZ", "name": "Ride Waves" },
    { "artist": "I Fight Dragons", "name": "Kaboom!" },
    { "artist": "Imagine Dragons", "name": "Night Visions" },
    { "artist": "Imagine Dragons", "name": "Smoke + Mirrors" },
    { "artist": "Indigo Girls", "name": "Rites of Passage" },
    { "artist": "Ingird Michaelson", "name": "Lights Out" },
    { "artist": "Israel Kamakawiwo'ole", "name": "Facing Future" },
    { "artist": "Jet", "name": "Get Born" },
    { "artist": "Joe Jackson", "name": "Look Sharp!" },
    { "artist": "Jonsi", "name": "Go" },
    { "artist": "Journey", "name": "Greatest Hits" },
    { "artist": "Julian Casablancas", "name": "Phrazes For The Young" },
    { "artist": "K.Flay", "name": "Every Where Is Some Where" },
    { "artist": "Kansas", "name": "Point Of Know Return" },
    { "artist": "Kasabian", "name": "Velociraptor!" },
    { "artist": "Kasabian", "name": "West Ryder Pauper Lunatic Asylum" },
    { "artist": "Kate Bush", "name": "Hounds of Love" },
    { "artist": "KT Tunstall", "name": "Eye To The Telescope" },
    { "artist": "KT Tunstall", "name": "KIN" },
    { "artist": "KT Tunstall", "name": "Tiger Suit" },
    { "artist": "Lady Gaga", "name": "The Fame Monster" },
    { "artist": "LCD Soundsystem", "name": "Sound Of Silver" },
    { "artist": "LCD Soundsystem", "name": "This Is Happening" },
    { "artist": "Led Zeppelin", "name": "IV" },
    { "artist": "Led Zeppelin", "name": "Led Zeppelin III (2014 Remaster)" },
    { "artist": "Led Zeppelin", "name": "Physical Graffiti" },
    { "artist": "Lifehouse", "name": "Almeria" },
    { "artist": "Lifehouse", "name": "Who We Are" },
    { "artist": "Linkin Park", "name": "Meteora" },
    { "artist": "Logic", "name": "Confessions Of A Dangerous Mind" },
    { "artist": "London Grammar", "name": "If You Wait" },
    { "artist": "Lorde", "name": "Pure Heroine" },
    { "artist": "Lupe Fiasco", "name": "Lasers" },
    { "artist": "Lupe Fiasco", "name": "Lupe Fiasco's The Cool" },
    { "artist": "M83", "name": "Hurry Up, We're Dreaming" },
    { "artist": "Macklemore & Ryan Lewis", "name": "The Heist" },
    { "artist": "Maroon 5", "name": "Hands All Over" },
    { "artist": "Maroon 5", "name": "Songs About Jane" },
    { "artist": "Massive Attack", "name": "Blue Lines" },
    { "artist": "Matisyahu", "name": "Spark Seeker" },
    { "artist": "Highly Suspect", "name": "MCID" },
    { "artist": "Meat Loaf", "name": "Bat Out Of Hell" },
    { "artist": "Metric", "name": "Fantasies" },
    { "artist": "Metric", "name": "Synthetica" },
    { "artist": "Michael Franti", "name": "All Rebel Rockers" },
    { "artist": "Michael Franti", "name": "All People" },
    { "artist": "Michael Franti", "name": "Yell Fire!" },
    { "artist": "Michael Jackson", "name": "Off The Wall" },
    { "artist": "Mike Doughty", "name": "Haughty Melodic" },
    { "artist": "Milky Chance", "name": "Blossom" },
    { "artist": "Milky Chance", "name": "Mind the Moon" },
    { "artist": "Mister Wives", "name": "Connect The Dots" },
    { "artist": "Modest Mouse", "name": "Good News for People Who Love Bad News" },
    { "artist": "Moon Taxi", "name": "Let The Record Play" },
    { "artist": "Mumford & Sons", "name": "Babel" },
    { "artist": "Murs", "name": "A Strange Journey Into The Unimaginable" },
    { "artist": "Muse", "name": "Simulation Theory" },
    { "artist": "Muse", "name": "The Resistance" },
    { "artist": "Neon Trees", "name": "Picture Show" },
    { "artist": "Neon Trees", "name": "Pop Psychology" },
    { "artist": "Nirvana", "name": "Nevermind" },
    { "artist": "Nirvana", "name": "Nirvana" },
    { "artist": "Noel Gallagher's High Flying Birds", "name": "Who Built The Moon?" },
    { "artist": "Nothing But Thieves", "name": "Nothing But Thieves" },
    { "artist": "Nothing More", "name": "The Stories We Tell Ourselves" },
    { "artist": "Of Monsters And Men", "name": "FEVER DREAM" },
    { "artist": "Of Monsters And Men", "name": "My Head Is An Animal" },
    { "artist": "OneRepublic", "name": "Dreaming Out Loud" },
    { "artist": "OneRepublic", "name": "Native" },
    { "artist": "OneRepublic", "name": "Waking Up" },
    { "artist": "Orishas", "name": "Gourmet" },
    { "artist": "Ozomotli", "name": "Embrace The Chaos" },
    { "artist": "P!nk", "name": "The Truth About Love" },
    { "artist": "Panda Bear", "name": "Panda Bear Meets The Grim Reaper" },
    { "artist": "Panic! At The Disco", "name": "Pray For The Wicked" },
    { "artist": "Passion Pit", "name": "Kindred" },
    { "artist": "Pet Shop Boys", "name": "Please" },
    { "artist": "Pete Townshend", "name": "Empty Glass" },
    { "artist": "P!nk", "name": "Try This" },
    { "artist": "Pink Floyd", "name": "The Wall" },
    { "artist": "Pink Floyd", "name": "Dark Side Of The Moon" },
    { "artist": "Plan B", "name": "Heaven Before All Hell Breaks Loose" },
    { "artist": "Portishead", "name": "Dummy" },
    { "artist": "Prince", "name": "Purple Rain" },
    { "artist": "Prophets of Rage", "name": "Prophets or Rage" },
    { "artist": "Queen", "name": "A Night At The Opera" },
    { "artist": "Queen", "name": "Jazz" },
    { "artist": "Queen", "name": "News Of The World" },
    { "artist": "Queen", "name": "The Game" },
    { "artist": "Queens Of The Stone Age", "name": "Villains" },
    { "artist": "Red Hot Chili Peppers", "name": "Californication" },
    { "artist": "Red Hot Chili Peppers", "name": "Stadium Arcadium" },
    { "artist": "Rodrigo Y Gabriela", "name": "Rodrigo Y Gabriela" },
    { "artist": "Ryan Bingham", "name": "Junky Star" },
    { "artist": "Ryan Bingham", "name": "Mescalito" },
    { "artist": "Santana", "name": "Supernatural" },
    { "artist": "Seether", "name": "Holding Onto Strings Better Left To Fray" },
    { "artist": "Shaggy", "name": "Wah Gwaan?!" },
    { "artist": "Shinedown", "name": "Amaryllis" },
    { "artist": "Shiny Toy Guns", "name": "Season Of Poison" },
    { "artist": "Shovels & Rope", "name": "O Be Joyful" },
    { "artist": "Shovels & Rope", "name": "Swimmin Time" },
    { "artist": "Silversun Pickups", "name": "Carnavas" },
    { "artist": "Silversun Pickups", "name": "Neck Of The Woods" },
    { "artist": "Silversun Pickups", "name": "Swoon" },
    { "artist": "Sixpence None The Richer", "name": "Lost In Translation" },
    { "artist": "Smashing Pumpkins", "name": "Oceania" },
    { "artist": "Snow Patrol", "name": "Eyes Open" },
    { "artist": "Snow Patrol", "name": "Wildness" },
    { "artist": "Spoon", "name": "Ga Ga Ga Ga Ga" },
    { "artist": "Stick Figure", "name": "Set In Stone" },
    { "artist": "Sting", "name": "The Dream Of The Blue Turtles" },
    { "artist": "Supertramp", "name": "Crime Of The Century" },
    { "artist": "Sweet", "name": "Desolation Boulevard" },
    { "artist": "Switchfoot", "name": "Fading West" },
    { "artist": "SYML", "name": "SYML" },
    { "artist": "Tears For Fears", "name": "Sowing The Seeds Of Love" },
    { "artist": "The 1975", "name": "The 1975" },
    { "artist": "The All-American Rejects", "name": "Move Along" },
    { "artist": "The B-52s", "name": "The B-52s" },
    { "artist": "The Black Keys", "name": "Brothers" },
    { "artist": "The Black Keys", "name": "Magic Potion" },
    { "artist": "The Cars", "name": "Candy-O" },
    { "artist": "The Cars", "name": "The Cars" },
    { "artist": "The Civil Wars", "name": "Barton Hollow" },
    { "artist": "The Cranberries", "name": "In The End" },
    { "artist": "The Cure", "name": "Kiss Me, Kiss Me, Kiss Me" },
    { "artist": "The Decemberists", "name": "I'll Be Your Girl" },
    { "artist": "The Doors", "name": "L.A. Woman" },
    { "artist": "The Fratellis", "name": "In Your Own Sweet Time" },
    { "artist": "The Fray", "name": "How To Save A Life" },
    { "artist": "The Gaslight Anthem", "name": "Handwritten" },
    { "artist": "The Gaslight Anthem", "name": "The '59 Sound" },
    { "artist": "The Head And The Heart", "name": "Let's Be Still" },
    { "artist": "The Head And The Heart", "name": "Living Mirage" },
    { "artist": "The Heavy", "name": "The Glorious Dead" },
    { "artist": "The Heavy", "name": "The House That Dirt Built" },
    { "artist": "The Killers", "name": "Hot Fuss" },
    { "artist": "The Killers", "name": "Wonderful Wonderful" },
    { "artist": "The Lone Bellow", "name": "Walking Into A Storm" },
    { "artist": "The Naked And Famous", "name": "Passive Me, Aggressive You" },
    { "artist": "The Offspring", "name": "Days Go By" },
    { "artist": "The Pains Of Being Pure At Heart", "name": "Days Of Abandon" },
    { "artist": "The Postal Service", "name": "Give Up" },
    { "artist": "The Raconteurs", "name": "Consolers Of The Lonely" },
    { "artist": "The Sheepdogs", "name": "Changing Colours" },
    { "artist": "The Sheepdogs", "name": "The Sheepdogs" },
    { "artist": "The Shins", "name": "Heartworms" },
    { "artist": "The Shins", "name": "Port Of Morrow" },
    { "artist": "The Shins", "name": "Wincing The Night Away" },
    { "artist": "The Wallflowers", "name": "Glad All Over" },
    { "artist": "The Who", "name": "Who's Next" },
    { "artist": "The xx", "name": "The xx" },
    { "artist": "Toto", "name": "IV" },
    { "artist": "twenty one pilots", "name": "Blurryface" },
    { "artist": "USS (Ubiquitous Synergy Seeker)", "name": "Questamation" },
    { "artist": "Vampire Weekend", "name": "Contra" },
    { "artist": "Vampire Weekend", "name": "Father Of The Bride" },
    { "artist": "Vic Mensa", "name": "The Autobiography" },
    { "artist": "Violent Femmes", "name": "Violent Femmes" },
    { "artist": "Volbeat", "name": "Guitar Gangsters & Cadillac Blood" },
    { "artist": "Walk Off The Earth", "name": "Sing It All Away" },
    { "artist": "Warren Zevon", "name": "Excitable Boy" },
    { "artist": "Weezer", "name": "Weezer (Blue Album)" },
    { "artist": "Welshly Arms", "name": "No Place Is Home" },
    { "artist": "Wild Belle", "name": "Isles" },
    { "artist": "Wisin", "name": "Victory" },
    { "artist": "Wisin Y Yandel", "name": "Líderes" },
    { "artist": "Yaz", "name": "Upstairs At Eric's" },
    { "artist": "Yeasayer", "name": "Odd Blood" },
    { "artist": "Young the Giant", "name": "Home Of The Strange" },
    { "artist": "Young the Giant", "name": "Mind Over Matter" },
    { "artist": "Young the Giant", "name": "Mirror Master" },
    { "artist": "ZZ Top", "name": "Eliminator" },
    { "artist": "Bombay Bicycle Club", "name": "Everything Else Has Gone Wrong" },
    { "artist": "The Sounds", "name": "Dying To Say This To You" },
    { "artist": "SuperHeavy", "name": "SuperHeavy" },
    { "artist": "The Constelations", "name": "Southern Gothic" },
    { "artist": "Under the Influence of Giants", "name": "Under the Influence of Giants" },
    { "artist": "Morning Parade", "name": "Morning Parade" },
    { "artist": "Wale", "name": "Wow...That's Crazy" },
    { "artist": "Airborne Toxic Event", "name": "Dope Machines" },
    { "artist": "J. Roddy Walston & The Business", "name": "Essential Tremors" },
    { "artist": "The Decemberists", "name": "The King Is Dead" },
    { "artist": "IAMDYNAMITE", "name": "Supermegafantastic" },
    { "artist": "Dispatch", "name": "Circles Around The Sun" },
    { "artist": "Man Man", "name": "On Oni Pond" },
    { "artist": "Switchfoot", "name": "Hello Hurricane" },
    { "artist": "Minus the Bear", "name": "Omni" },
    { "artist": "White Lies", "name": "To Lose My Life ..." },
    { "artist": "Dave Mathews Band", "name": "Crash" },
    { "artist": "Sia", "name": "1000 Forms of Fear" },
    { "artist": "Tom Petty", "name": "Full Moon Fever" },
    { "artist": "Plain White T's", "name": "All That We Needed" },
    { "artist": "Sea Wolf", "name": "Leaves in the River" },
    { "artist": "Benjamin Gibbard", "name": "Former Lives" },
    { "artist": "Sting", "name": "Brand New Day" },
    { "artist": "Michael Jackson", "name": "Thriller" },
    { "artist": "Milky Chance", "name": "Sadnecessary" }];
